name: miniui_component
description: "A lightweight Flutter UI component library built on widgets without material.dart."

version: 0.0.3

environment:
  sdk: ^3.11.4

homepage: https://github.com/ar-insect/miniui_component
repository: https://github.com/ar-insect/miniui_component
issue_tracker: https://github.com/ar-insect/miniui_component/issues

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
